### ISSUE TITLE
大佬，能不能出去教程讲讲oss图床怎么使用？

### ISSUE THREAD

**Issue by wjkcxs** [Tualin14/OneSS#23]
鄙人为一名想用onss给自己的个人博客整一个图床，可是不知道怎么使用，能否讲解一下呀？

**Comment by Tualin14** [comment]
就是图片传上去，复制链接放到你要用的地方就行了，action图标的第3个，复制出来类似这样
`https://oss.dza.vin/api/item/content?user=share@dzaaaaaa.com&id=013EY5Y6AVMSB3PQOMVZF3CJPIJFIEVPRX`

**Comment by Tualin14** [comment]
但是其实现在我认为如果就图片的话不如放到cloudflare或者一些静态服务上，这个OneSS用来放视频，音乐之类的比较好

**Comment by wjkcxs** [comment]
还想问一下，我想在主页添加其他频道的链接话怎么办，预选项好像只有那几个e-mail，哔哩哔哩之类的。

**Comment by Tualin14** [comment]
你要那些？一般常用的我直接加里面，最好是有图标> 还想问一下，我想在主页添加其他频道的链接话怎么办，预选项好像只有那几个e-mail，哔哩哔哩之类的。

**Comment by wjkcxs** [comment]
西瓜视频，爱奇艺，喜马拉雅，新浪微博，acfun，抖音这些。

**Comment by Tualin14** [comment]
这些有图标吗？似乎有些图标不好找。文档加使用说明和增加社交图标与链接加到今天计划里了。

**Comment by wjkcxs** [comment]
感谢大佬，能不能专门出一个服务链接管理的界面，我看其他人好像都是拿他来做博客视频和照片储存工具的，如果能加上的话效率能大大提高。(´∇ﾉ｀*)ノ

**Comment by Tualin14** [comment]
服务链接管理界面具体是什么样的？要有什么功能？我没明白啥意思(/ω＼)

**Comment by wjkcxs** [comment]
有人给我推荐了这样一个网站
https://poweredby.cloud/?utm_source=zhihu
这样类似的？

**Comment by Tualin14** [comment]
我觉得不需要这个东西吧，要用的东西复制链接过去就行，只要不在onedrive删除，不改域名，只是在文件夹移动或者改名是不会影响找不到文件的。如果为了方便管理，同类东西都放一个文件夹就好了。

你说的一定需要这个管理界面的点在哪里？可能我还是没理解你的意思……

**Comment by wjkcxs** [comment]
那行吧，这样只会徒增大佬的工作负担，大佬还是要劳逸结合，注意身体，第一次提问感觉自己跟甲方一样，以后我自己还是得多注意注意说话口气，再见。

**Comment by Tualin14** [comment]
说话语气什么的怎样都行，主要是我真没明白，抱歉orz。

而且这个不应该放在博客哪里，而不应该是这边吧。

**Comment by Tualin14** [comment]
添加使用说明和一些社交图标，并且可自定义添加更多的社交图标 #24
