### ISSUE TITLE
显示

### ISSUE THREAD

**Issue by wjkcxs** [Tualin14/OneSS#25]
好像阿婆主你添加完新功能以后爆bug了。
![屏幕截图 2022-05-01 210436](https://user-images.githubusercontent.com/91823010/166147238-83eb4938-d95a-4be0-a146-7f269241c0a9.png)

**Comment by wjkcxs** [comment]
手机版本好像也有些问题
![6V4KWAJL){BIYZ_R0LMR @8](https://user-images.githubusercontent.com/91823010/166147302-027d4283-6f38-4d13-9afe-acc1b5cdcab2.jpg)
。

**Comment by Tualin14** [comment]
哪里bug？手机可以右拖吧

如果你指界面的话，我改成了仿onedrive客户端
![正在上传 166152489...]

**Comment by Tualin14** [comment]
补上图片
![IMG_8606](https://user-images.githubusercontent.com/71857734/166152536-99019eca-5d08-4f36-a54a-48e434df0f54.jpeg)

**Comment by wjkcxs** [comment]
现在图片预览好像不能像之前一样显示全部图片，应该不能叫bug吧？进入share界面以后，才能查看到全部，之前好像可以。
![Screenshot_2022-05-02-07-11-44-834_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/91823010/166168675-f0cd5650-7701-42f2-bf48-1e4afbd814a7.jpg)
![Screenshot_2022-05-02-07-19-45-914_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/91823010/166168685-67334a1f-abf1-4dd3-8329-b1a26f6f7a69.jpg)

**Comment by Tualin14** [comment]
就是不是全的，我限制高度了，这样没有滚动条了，要不不统一。
图片不全也能分辨出是否是想要图片的。

**Comment by wjkcxs** [comment]
oh，懂了，那就这么用，谢谢哥。ꉂ(ˊᗜˋ*)

**Comment by Tualin14** [comment]
我今天看情况加一个点图片显示全部图片

**Comment by Tualin14** [comment]
啥东西？

**Comment by wjkcxs** [comment]
对不起，发错地方了。

**Comment by Tualin14** [comment]
[添加点图片显示完整图片功能](https://github.com/Tualin14/OneSS/commit/c8fea334c4f878e6c6a41f489b7ee6796e95f14f)
